name: Run B.R.I.E.F

on:
  schedule:
    - cron: '0 20 * * *'  # Runs every day at 3 PM EST (20:00 UTC)
  workflow_dispatch:  

jobs:
  run-brief:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.5'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the script
        env:
          SLACK_BOT_OAUTH: ${{ secrets.SLACK_BOT_OAUTH }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD}}
          OPENAI_API_KEY:  ${{secrets.OPENAI_API_KEY}}
        run: |
          python main.py